<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('brands')->insert([
            ['id' => '1',    'name' => 'Sem Marca', 'status' => '1', 'os_check' => '1'],
            ['id' => '2',    'name' => 'CellShopp', 'status' => '1', 'os_check' => '1'],
            ['id' => '3',    'name' => 'Acer', 'status' => '1', 'os_check' => '1'],
            //['id' => '4',    'name' => 'AGM', 'status' => '1', 'os_check' => '1'],
            ['id' => '5',    'name' => 'Alcatel', 'status' => '1', 'os_check' => '1'],
            ['id' => '6',    'name' => 'Amazon', 'status' => '1', 'os_check' => '1'],
            ['id' => '7',    'name' => 'Apple', 'status' => '1', 'os_check' => '1'],
            //['id' => '8',    'name' => 'Archos', 'status' => '1', 'os_check' => '1'],
            ['id' => '9',    'name' => 'Asus', 'status' => '1', 'os_check' => '1'],
            //['id' => '10',    'name' => 'Benefon', 'status' => '1', 'os_check' => '1'],
            ['id' => '11',    'name' => 'BenQ', 'status' => '1', 'os_check' => '1'],
            //['id' => '12',    'name' => 'BenQ-Siemens', 'status' => '1', 'os_check' => '1'],
            ['id' => '13',    'name' => 'BlackBerry', 'status' => '1', 'os_check' => '1'],
            //['id' => '14',    'name' => 'Blackview', 'status' => '1', 'os_check' => '1'],
            ['id' => '15',    'name' => 'Blu', 'status' => '1', 'os_check' => '1'],
            //['id' => '16',    'name' => 'Bluboo', 'status' => '1', 'os_check' => '1'],
            //['id' => '17',    'name' => 'Brionvega', 'status' => '1', 'os_check' => '1'],
            ['id' => '18',    'name' => 'Cat', 'status' => '1', 'os_check' => '1'],
            //['id' => '19',    'name' => 'CECT', 'status' => '1', 'os_check' => '1'],
            //['id' => '20',    'name' => 'Centric', 'status' => '1', 'os_check' => '1'],
            //['id' => '21',    'name' => 'Cubot', 'status' => '1', 'os_check' => '1'],
            //['id' => '22',    'name' => 'Daewoo', 'status' => '1', 'os_check' => '1'],
            //['id' => '23',    'name' => 'Dbtel', 'status' => '1', 'os_check' => '1'],
            ['id' => '24',    'name' => 'Dell', 'status' => '1', 'os_check' => '1'],
            //['id' => '25',    'name' => 'Elephone', 'status' => '1', 'os_check' => '1'],
            //['id' => '26',    'name' => 'EM2', 'status' => '1', 'os_check' => '1'],
            //['id' => '27',    'name' => 'Energizer', 'status' => '1', 'os_check' => '1'],
            //['id' => '28',    'name' => 'Enteos', 'status' => '1', 'os_check' => '1'],
            ['id' => '29',    'name' => 'Ericsson', 'status' => '1', 'os_check' => '1'],
            //['id' => '30',    'name' => 'Essential', 'status' => '1', 'os_check' => '1'],
            //['id' => '31',    'name' => 'Eten', 'status' => '1', 'os_check' => '1'],
            //['id' => '32',    'name' => 'Fujitsu-Siemens', 'status' => '1', 'os_check' => '1'],
            //['id' => '33',    'name' => 'Fxtec', 'status' => '1', 'os_check' => '1'],
            //['id' => '34',    'name' => 'Garmin Asus', 'status' => '1', 'os_check' => '1'],
            //['id' => '35',    'name' => 'Gigabyte', 'status' => '1', 'os_check' => '1'],
            //['id' => '36',    'name' => 'Gionee', 'status' => '1', 'os_check' => '1'],
            ['id' => '37',    'name' => 'Google', 'status' => '1', 'os_check' => '1'],
            //['id' => '38',    'name' => 'Grundig', 'status' => '1', 'os_check' => '1'],
            //['id' => '39',    'name' => 'Haier', 'status' => '1', 'os_check' => '1'],
            //['id' => '40',    'name' => 'Hewlett Packard', 'status' => '1', 'os_check' => '1'],
            //['id' => '41',    'name' => 'Hisense', 'status' => '1', 'os_check' => '1'],
            //['id' => '42',    'name' => 'HomTom', 'status' => '1', 'os_check' => '1'],
            //['id' => '43',    'name' => 'Honor', 'status' => '1', 'os_check' => '1'],
            //['id' => '44',    'name' => 'Hop Mobile', 'status' => '1', 'os_check' => '1'],
            ['id' => '45',    'name' => 'HP', 'status' => '1', 'os_check' => '1'],
            ['id' => '46',    'name' => 'HTC', 'status' => '1', 'os_check' => '1'],
            ['id' => '47',    'name' => 'Huawei', 'status' => '1', 'os_check' => '1'],
            //['id' => '48',    'name' => 'Hughes', 'status' => '1', 'os_check' => '1'],
            //['id' => '49',    'name' => 'i-Mate', 'status' => '1', 'os_check' => '1'],
            //['id' => '50',    'name' => 'Infinix', 'status' => '1', 'os_check' => '1'],
            //['id' => '51',    'name' => 'InFocus', 'status' => '1', 'os_check' => '1'],
            //['id' => '52',    'name' => 'Innostream', 'status' => '1', 'os_check' => '1'],
            //['id' => '53',    'name' => 'INQ', 'status' => '1', 'os_check' => '1'],
            //['id' => '54',    'name' => 'itel', 'status' => '1', 'os_check' => '1'],
            //['id' => '55',    'name' => 'Itelco', 'status' => '1', 'os_check' => '1'],
            //['id' => '56',    'name' => 'i-Teq', 'status' => '1', 'os_check' => '1'],
            //['id' => '57',    'name' => 'ITT', 'status' => '1', 'os_check' => '1'],
            //['id' => '58',    'name' => 'Jolla', 'status' => '1', 'os_check' => '1'],
            //['id' => '59',    'name' => 'Lava', 'status' => '1', 'os_check' => '1'],
            //['id' => '60',    'name' => 'LeEco', 'status' => '1', 'os_check' => '1'],
            ['id' => '61',    'name' => 'Lenovo', 'status' => '1', 'os_check' => '1'],
            ['id' => '62',    'name' => 'LG', 'status' => '1', 'os_check' => '1'],
            //['id' => '63',    'name' => 'Martin Dawes', 'status' => '1', 'os_check' => '1'],
            //['id' => '64',    'name' => 'Maze', 'status' => '1', 'os_check' => '1'],
            //['id' => '65',    'name' => 'Meizu', 'status' => '1', 'os_check' => '1'],
            //['id' => '66',    'name' => 'Micromax', 'status' => '1', 'os_check' => '1'],
            ['id1' => '67',    'name' => 'Microsoft', 'status' => '1', 'os_check' => '1'],
            //['id' => '68',    'name' => 'Mio', 'status' => '1', 'os_check' => '1'],
            //['id' => '69',    'name' => 'Mitsubishi', 'status' => '1', 'os_check' => '1'],
            //['id' => '70',    'name' => 'MOMO Design', 'status' => '1', 'os_check' => '1'],
            ['id' => '71',    'name' => 'Motorola', 'status' => '1', 'os_check' => '1'],
            ['id' => '72',    'name' => 'Multilaser', 'status' => '1', 'os_check' => '1'],
            //['id' => '73',    'name' => 'Nec', 'status' => '1', 'os_check' => '1'],
            //['id' => '74',    'name' => 'Neonode', 'status' => '1', 'os_check' => '1'],
            //['id' => '75',    'name' => 'NGM', 'status' => '1', 'os_check' => '1'],
            ['id' => '76',    'name' => 'Nokia', 'status' => '1', 'os_check' => '1'],
            //['id' => '77',    'name' => 'Nubia', 'status' => '1', 'os_check' => '1'],
            //['id' => '78',    'name' => 'Onda', 'status' => '1', 'os_check' => '1'],
            //['id' => '79',    'name' => 'OnePlus', 'status' => '1', 'os_check' => '1'],
            ['id' => '80',    'name' => 'Oppo', 'status' => '1', 'os_check' => '1'],
            //['id' => '81',    'name' => 'Oukitel', 'status' => '1', 'os_check' => '1'],
            //['id' => '82',    'name' => 'Palm', 'status' => '1', 'os_check' => '1'],
            //['id' => '83',    'name' => 'PalmOne', 'status' => '1', 'os_check' => '1'],
            ['id' => '84',    'name' => 'Panasonic', 'status' => '1', 'os_check' => '1'],
            //['id' => '85',    'name' => 'Pantech', 'status' => '1', 'os_check' => '1'],
            //['id' => '86',    'name' => 'Philco', 'status' => '1', 'os_check' => '1'],
            //['id' => '87',    'name' => 'Philips', 'status' => '1', 'os_check' => '1'],
            //['id' => '88',    'name' => 'PocketDevice', 'status' => '1', 'os_check' => '1'],
            ['id' => '89',    'name' => 'Poco', 'status' => '1', 'os_check' => '1'],
            //['id' => '90',    'name' => 'Porsche Design', 'status' => '1', 'os_check' => '1'],
            ['id' => '91',    'name' => 'Positivo', 'status' => '1', 'os_check' => '1'],
            //['id' => '92',    'name' => 'QQAAXX', 'status' => '1', 'os_check' => '1'],
            //['id' => '93',    'name' => 'Qtek', 'status' => '1', 'os_check' => '1'],
            ['id' => '94',    'name' => 'Quantum', 'status' => '1', 'os_check' => '1'],
            //['id' => '95',    'name' => 'Razer', 'status' => '1', 'os_check' => '1'],
            ['id' => '96',    'name' => 'Realme', 'status' => '1', 'os_check' => '1'],
            //['id' => '97',    'name' => 'RED', 'status' => '1', 'os_check' => '1'],
            ['id' => '98',    'name' => 'Redmi', 'status' => '1', 'os_check' => '1'],
            //['id' => '99',    'name' => 'RIM', 'status' => '1', 'os_check' => '1'],
            //['id' => '100',    'name' => 'Royole', 'status' => '1', 'os_check' => '1'],
            //['id' => '101',    'name' => 'Sagem', 'status' => '1', 'os_check' => '1'],
            ['id' => '102',    'name' => 'Samsung', 'status' => '1', 'os_check' => '1'],
            //['id' => '103',    'name' => 'Sendo', 'status' => '1', 'os_check' => '1'],
            //['id' => '104',    'name' => 'Sharp', 'status' => '1', 'os_check' => '1'],
            ['id' => '105',    'name' => 'Siemens', 'status' => '1', 'os_check' => '1'],
            //['id' => '106',    'name' => 'Siemens-Xelibri', 'status' => '1', 'os_check' => '1'],
            //['id' => '107',    'name' => 'Sonim', 'status' => '1', 'os_check' => '1'],
            ['id' => '108',    'name' => 'Sony', 'status' => '1', 'os_check' => '1'],
            //['id' => '109',    'name' => 'Sony Ericsson', 'status' => '1', 'os_check' => '1'],
            ['id' => '110',    'name' => 'TCL', 'status' => '1', 'os_check' => '1'],
            //['id' => '111',    'name' => 'TECNO', 'status' => '1', 'os_check' => '1'],
            //['id' => '112',    'name' => 'Tectoy', 'status' => '1', 'os_check' => '1'],
            //['id' => '113',    'name' => 'Tel.Me', 'status' => '1', 'os_check' => '1'],
            //['id' => '114',    'name' => 'Telit', 'status' => '1', 'os_check' => '1'],
            //['id' => '115',    'name' => 'Thuraya', 'status' => '1', 'os_check' => '1'],
            //['id' => '116',    'name' => 'Toshiba', 'status' => '1', 'os_check' => '1'],
            //['id' => '117',    'name' => 'TP-Link', 'status' => '1', 'os_check' => '1'],
            //['id' => '118',    'name' => 'Ulefone', 'status' => '1', 'os_check' => '1'],
            //['id' => '119',    'name' => 'UMI', 'status' => '1', 'os_check' => '1'],
            //['id' => '120',    'name' => 'UMIDIGI', 'status' => '1', 'os_check' => '1'],
            ['id' => '121',    'name' => 'Vaio', 'status' => '1', 'os_check' => '1'],
            //['id' => '122',    'name' => 'Vernee', 'status' => '1', 'os_check' => '1'],
            //['id' => '123',    'name' => 'Vertu', 'status' => '1', 'os_check' => '1'],
            //['id' => '124',    'name' => 'vivo', 'status' => '1', 'os_check' => '1'],
            //['id' => '125',    'name' => 'VK Mobile', 'status' => '1', 'os_check' => '1'],
            //['id' => '126',    'name' => 'Vodafone', 'status' => '1', 'os_check' => '1'],
            //['id' => '127',    'name' => 'Wiko', 'status' => '1', 'os_check' => '1'],
            ['id' => '128',    'name' => 'Xiaomi', 'status' => '1', 'os_check' => '1'],
            //['id' => '129',    'name' => 'Xolo', 'status' => '1', 'os_check' => '1'],
            //['id' => '130',    'name' => 'Xplore', 'status' => '1', 'os_check' => '1'],
            ['id' => '131',    'name' => 'ZTE', 'status' => '1', 'os_check' => '1'],
        ]);
    }
}
