image: edbizarro/gitlab-ci-pipeline-php:7.4
#
#services:
# - mariadb:10.5.8
#
#variables:
#  MYSQL_DATABASE: shoppcelldb
#  MYSQL_ROOT_PASSWORD: 5#24##2019shoppcell
#  DB_HOST: mysql
#  DB_USERNAME: shoppcelluserdb

stages:
#  - build
#  - test
  - deploy

#composer:
#  stage: build
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-composer
#    paths:
#      - vendor/
#  script:
#      - composer install
#      - cp .env.example .env
#      - php artisan key:generate
#      - php artisan migrate:fresh
#      - npm install
#      - npm run dev
#      - php artisan passport:install
#  artifacts:
#    expire_in: 1 day
#    paths:
#      - vendor/
#      - .env
#
#codestyle:
#  stage: test
#  dependencies: []
#  script:
#    - composer global require "squizlabs/php_codesniffer=*"
#    - ~/.composer/vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app
#  allow_failure: true
#
#unit_test:
#  stage: test
#  script:
#    - phpunit --coverage-text --colors=never
#  allow_failure: true
#
#staging:
#  stage: deploy
#  script:
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#    - eval $(ssh-agent -s)
#    - ssh-add <(echo "$SSH_PRIVATE_KEY")
#    - mkdir -p ~/.ssh
#    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#    - composer global require laravel/envoy
#    - ~/.composer/vendor/bin/envoy run deploy_staging --commit="$CI_COMMIT_SHA"
#  environment:
#    name: staging
#    url: http://staging-api.influu.me
#  when: on_success
#  only:
#    - master
production:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - composer global require laravel/envoy
    - ~/.composer/vendor/bin/envoy run deploy_production --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: http://app.lojashoppcell.com.br
  when: on_success
  only:
    - master
